index:
   path: /user/
   controller: App\Controller\UserController::index
newUser:
   path: user/new
   controller: App\Controller\UserController::newUser
api_user:
   path: user/new
   controller: App\Controller\UserController::api_user
delete: 
   path: user/delete/{id}
   controller : App\Controller\UserController::delete
